### ISSUE TITLE
Set Context Path

### ISSUE THREAD

**Issue by matheusgr** [AlbuquerqueRafael/Dilettante-Server#20]
https://github.com/AlbuquerqueRafael/Dilettante-Server/blob/5224228463a0d4d313a96c34f05e21105c7eda4a/src/main/java/com/api/dl/publication/PublicationController.java#L18

the "/api" resource path is called a context path. one should avoid to set it during the request mapping. if i need to set the mapping to /api_v1 or /api_v2 it would be hard to do so in your application.

you can use the contextPath server property (see app configuration) as follow:

server.contextPath=/api

**Comment by AlbuquerqueRafael** [comment]
-Done: https://github.com/AlbuquerqueRafael/Dilettante-Server/pull/23
