### ISSUE TITLE
Ant Matchers supports **

### ISSUE THREAD

**Issue by matheusgr** [AlbuquerqueRafael/Dilettante-Server#21]
You may use wildcards on antmatchers path. ** is used to represent a deep match /example/** -> matches both /example/a as /example/b/c

https://github.com/AlbuquerqueRafael/Dilettante-Server/blob/5224228463a0d4d313a96c34f05e21105c7eda4a/src/main/java/com/api/dl/security/WebSecurityConfig.java#L35

**Comment by AlbuquerqueRafael** [comment]
Maybe I will need some "get publication" resources with a need for auth in the future. This is why I decided to not use wildcards.
